version: '3.4'

services:
  dockertestwebapi:
    build:
      context: .
      dockerfile: DockerTestWebapi/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "tester@12345"
      ACCEPT_EULA: "Y"